version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: ryansgot/android:android-27-with-api26-emulator
    environment:
#      QEMU_AUDIO_DRV: none
      GIT_AUTHOR_NAME: circleci
      GIT_AUTHOR_EMAIL: noreply@circleci.com
      GIT_COMMITTER_NAME: circleci
      GIT_COMMITTER_EMAIL: noreply@circleci.com
      EMAIL: noreply@circleci.com
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-window
          background: true
          environment:
            TERM: dumb
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "library/build.gradle" }}
      - run:
          name: Wait for emulator
          command: chmod +x scripts/android-wait-for-boot.sh && ./scripts/android-wait-for-boot.sh
          environment:
            TERM: dumb
      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb
      - run:
          name: Create Merged Reports
          command: ./gradlew :forsuredbandroid:createMergedReports
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash) -Z -t $CODECOV_TOKEN
      - store_artifacts:
          path: forsuredbandroid/build/reports
          destination: reports
      - store_test_results:
          path: forsuredbandroid/build/test-results